// Package interfaces ...
package interfaces

import "RoastWear/internal/models"

// UserRepository ...
//
// Methods:
//   - CreateUser: ...
//   - DeleteUser: ...
//   - HasUser: ...
//   - GetUser: ...
//   - GetAllUsers: ...
type UserRepository interface {
	CreateUser(user *models.User) error
	DeleteUser(user *models.User) error
	HasUser(field string, value interface{}) bool
	GetUser(field string, value interface{}) (*models.User, error)
	GetAllUsers() ([]models.User, error)
}
