// Package models ...
package models

// UserLoginRequest ...
//
// Fields:
//   - Username: ...
//   - Password: ...
type UserLoginRequest struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}
