// Package models ...
package models

import (
	"gorm.io/gorm"
)

// User ...
//
// Fields:
//   - ID: ...
//   - CreatedAt: ...
//   - UpdatedAt: ...
//   - DeletedAt: ...
//   - Username: ...
//   - Email: ...
//   - Password: ...
type User struct {
	gorm.Model
	Username string `gorm:"uniqueIndex;not null"`
	Email    string `gorm:"uniqueIndex;not null"`
	Password string `gorm:"not null"`
	Role     string `gorm:"not null;default:'user'"`
}
