// Package models ...
package models

// UserRegisterRequest ...
//
// Fields:
//   - Username: ...
//   - Email: ...
//   - Password: ...
type UserRegisterRequest struct {
	Username string `json:"username" validate:"required,min=3,max=20"`
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=8,max=128"`
}
